-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.users
(
    user_id integer NOT NULL GENERATED ALWAYS AS IDENTITY,
    username character varying(50) NOT NULL,
    email character varying(255) NOT NULL,
    password_hash text NOT NULL,
    role text NOT NULL DEFAULT 'user',
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    PRIMARY KEY (user_id),
    CONSTRAINT "unique email" UNIQUE (email),
    CONSTRAINT "unique username" UNIQUE (username),
	CONSTRAINT users_role_check CHECK (role IN ('admin', 'user', 'arbiter'))
);

COMMENT ON COLUMN public.users.role
    IS 'make sure to do the check role in bit:  CONSTRAINT users_role_check CHECK (role IN (''''admin'',
  ''user'', ''arbiter''))';

CREATE TABLE IF NOT EXISTS public.media
(
    media_id integer NOT NULL GENERATED ALWAYS AS IDENTITY,
    type character varying(50) NOT NULL,
    title character varying(255) NOT NULL,
    release_date date,
    cover_url text,
    genre text[],
    PRIMARY KEY (media_id),
	CONSTRAINT media_type_check CHECK (type in ('game', 'music', 'movie', 'tv', 'book'))
);

COMMENT ON TABLE public.media
    IS 'again needs this constraint check later: CONSTRAINT media_type_check CHECK (media_type IN (''game'',
  ''music'', ''movie'', ''tv'', ''book''))';

CREATE TABLE IF NOT EXISTS public.game_details
(
    developer character varying(255),
    publisher character varying(255),
    platforms text[],
    igdb_id integer,
    igdb_image_id character varying(50),
    steam_app_id integer,
    media_id integer NOT NULL,
    PRIMARY KEY (media_id),
    CONSTRAINT "unique igdb_id" UNIQUE (igdb_id),
    CONSTRAINT "unique steam_app_id" UNIQUE (steam_app_id)
);

CREATE TABLE IF NOT EXISTS public.music_details
(
    media_id integer NOT NULL,
    artist character varying(255) NOT NULL,
    format character varying(10),
    label character varying(255),
    track_count integer,
    PRIMARY KEY (media_id),
	CONSTRAINT music_format_check CHECK (format IN ('album', 'ep', 'single'))
);

COMMENT ON TABLE public.music_details
    IS 'format refers to ep, album single';

CREATE TABLE IF NOT EXISTS public.movie_details
(
    media_id integer NOT NULL,
    director character varying(255),
    studio character varying(255),
    length_minutes integer,
    PRIMARY KEY (media_id)
);

CREATE TABLE IF NOT EXISTS public.tv_details
(
    media_id integer NOT NULL,
    creator character varying(255),
    network character varying(255),
    season_count integer,
    PRIMARY KEY (media_id)
);

CREATE TABLE IF NOT EXISTS public.book_details
(
    media_id integer NOT NULL,
    author character varying(255),
    publisher character varying(255),
    isbn character varying(13),
    page_count integer,
    format text[],
    PRIMARY KEY (media_id)
);

COMMENT ON TABLE public.book_details
    IS 'format refers to: ebook, hardcover, paperback, audio book, etc. ';

CREATE TABLE IF NOT EXISTS public.reviews
(
    review_id integer NOT NULL GENERATED ALWAYS AS IDENTITY,
    media_id integer NOT NULL,
    author_id integer NOT NULL,
    title character varying(255) NOT NULL,
    body text NOT NULL,
    rating integer NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone,
    PRIMARY KEY (review_id),
	CONSTRAINT reviews_rating_check CHECK (rating BETWEEN 1 AND 10)
);

CREATE TABLE IF NOT EXISTS public.comments
(
    comment_id integer NOT NULL GENERATED ALWAYS AS IDENTITY,
    review_id integer NOT NULL,
    user_id integer NOT NULL,
    body text NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    PRIMARY KEY (comment_id)
);

CREATE TABLE IF NOT EXISTS public.review_reactions
(
    user_id integer NOT NULL,
    review_id integer NOT NULL,
    value smallint NOT NULL,
    PRIMARY KEY (user_id, review_id),
	CONSTRAINT review_reactions_value_check CHECK (value IN (1,-1))
);

ALTER TABLE IF EXISTS public.game_details
    ADD FOREIGN KEY (media_id)
    REFERENCES public.media (media_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public.music_details
    ADD FOREIGN KEY (media_id)
    REFERENCES public.media (media_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public.movie_details
    ADD FOREIGN KEY (media_id)
    REFERENCES public.media (media_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public.tv_details
    ADD FOREIGN KEY (media_id)
    REFERENCES public.media (media_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public.book_details
    ADD FOREIGN KEY (media_id)
    REFERENCES public.media (media_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public.reviews
    ADD FOREIGN KEY (media_id)
    REFERENCES public.media (media_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.reviews
    ADD FOREIGN KEY (author_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.comments
    ADD FOREIGN KEY (review_id)
    REFERENCES public.reviews (review_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public.comments
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.review_reactions
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.review_reactions
    ADD FOREIGN KEY (review_id)
    REFERENCES public.reviews (review_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE
    NOT VALID;

END;